# Generated by Django 2.1.1 on 2019-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0004_auto_20190208_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('notice_no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('notice_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='image',
            field=models.ImageField(blank='True', upload_to=''),
        ),
    ]
