# Generated by Django 2.1.1 on 2019-02-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0006_auto_20190213_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
    ]
