# Generated by Django 2.1.1 on 2019-02-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarcker', models.IntegerField(default=0)),
            ],
        ),
    ]
